name:                haskell-katas
version:             0.1.0.0
github:              "tbsklg/haskell-katas"
license:             BSD3
author:              "Tobias Klug"
maintainer:          "tbs.klg@gmail.com"
copyright:           "2021 Tobias Klug"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-katas#readme>

dependencies:
- base >= 4.7 && < 5
- split >= 0.2.3.5
- text == 2.0.2
- time == 1.12.2
- parsec == 3.1.16.1
- array >= 0.5.6.0
library:
  source-dirs: src
  dependencies:
    - containers

executables:
  haskell-katas-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-katas

tests:
  haskell-katas-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-katas
    - hspec >= 2.10.10
    - QuickCheck == 2.14.3
    - HUnit == 1.6.2.0
    - haskell-src-exts == 1.23.*
    - containers
